Feature/tc 56
CodeEnthusiasts/TrainingCenter pull request #61
Opened 2020-10-27 19:17 UTC by CcConStanTine

2020-10-27 22:12 UTC, naslakboss requested changes
Wonderful abstract code, chlop.. I saw only two small naming convention

2020-10-27 22:12 UTC, naslakboss commented on src/main/java/codeenthusiast/TrainingCenterApp/exercise/strengthexercise/keytechniqueelement/KeyTechniqueController.java
> +public class KeyTechniqueController extends AbstractController<KeyTechniqueElement, KeyTechniqueElementDTO> {
You should stick to one version of KeyTechnique : KeyTechnique or KeyTechniqueElements

2020-10-27 22:12 UTC, naslakboss commented on src/test/java/codeenthusiast/TrainingCenterApp/exercise/strengthexercise/keytechniqueelement/KeyTechniqueElementServiceImplTest.java
> +        keyTechniqueElement3 = new KeyTechniqueElement("Napnij mięsnie brzucha");
We should choose one convention and use only english or only polish in test data fragments of code

2020-10-28 06:04 UTC, CcConStanTine reviewed
Understood.

2020-10-28 06:05 UTC, CcConStanTine reviewed
Understood

2020-10-28 06:16 UTC, naslakboss approved these changes

2020-10-28 06:16 UTC, merged